package com.srsoft.model;

import java.util.Date;

public class Attendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.userId
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.startTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.endTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.createTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.updateTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.ip
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.remark
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.zaot
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Integer zaot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.chid
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Integer chid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.dakDate
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Date dakdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.iperror
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    private Integer iperror;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.userId
     *
     * @return the value of attendance.userId
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.userId
     *
     * @param userid the value for attendance.userId
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.startTime
     *
     * @return the value of attendance.startTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.startTime
     *
     * @param starttime the value for attendance.startTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.endTime
     *
     * @return the value of attendance.endTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.endTime
     *
     * @param endtime the value for attendance.endTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.createTime
     *
     * @return the value of attendance.createTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.createTime
     *
     * @param createtime the value for attendance.createTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.updateTime
     *
     * @return the value of attendance.updateTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.updateTime
     *
     * @param updatetime the value for attendance.updateTime
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.ip
     *
     * @return the value of attendance.ip
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.ip
     *
     * @param ip the value for attendance.ip
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.remark
     *
     * @return the value of attendance.remark
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.remark
     *
     * @param remark the value for attendance.remark
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.zaot
     *
     * @return the value of attendance.zaot
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Integer getZaot() {
        return zaot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.zaot
     *
     * @param zaot the value for attendance.zaot
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setZaot(Integer zaot) {
        this.zaot = zaot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.chid
     *
     * @return the value of attendance.chid
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.chid
     *
     * @param chid the value for attendance.chid
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.dakDate
     *
     * @return the value of attendance.dakDate
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Date getDakdate() {
        return dakdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.dakDate
     *
     * @param dakdate the value for attendance.dakDate
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setDakdate(Date dakdate) {
        this.dakdate = dakdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.iperror
     *
     * @return the value of attendance.iperror
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public Integer getIperror() {
        return iperror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.iperror
     *
     * @param iperror the value for attendance.iperror
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    public void setIperror(Integer iperror) {
        this.iperror = iperror;
    }
}