package com.srsoft.model;

import java.util.Date;

public class Calendar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.id
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.calendarType
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private Integer calendartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.eventName
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private String eventname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.envetDetail
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private String envetdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.createTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.owner
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.startEndTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    private String startendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.id
     *
     * @return the value of calendar.id
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.id
     *
     * @param id the value for calendar.id
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.calendarType
     *
     * @return the value of calendar.calendarType
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Integer getCalendartype() {
        return calendartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.calendarType
     *
     * @param calendartype the value for calendar.calendarType
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setCalendartype(Integer calendartype) {
        this.calendartype = calendartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.eventName
     *
     * @return the value of calendar.eventName
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public String getEventname() {
        return eventname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.eventName
     *
     * @param eventname the value for calendar.eventName
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setEventname(String eventname) {
        this.eventname = eventname == null ? null : eventname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.envetDetail
     *
     * @return the value of calendar.envetDetail
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public String getEnvetdetail() {
        return envetdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.envetDetail
     *
     * @param envetdetail the value for calendar.envetDetail
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setEnvetdetail(String envetdetail) {
        this.envetdetail = envetdetail == null ? null : envetdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.createTime
     *
     * @return the value of calendar.createTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.createTime
     *
     * @param createtime the value for calendar.createTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.owner
     *
     * @return the value of calendar.owner
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.owner
     *
     * @param owner the value for calendar.owner
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.startEndTime
     *
     * @return the value of calendar.startEndTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public String getStartendtime() {
        return startendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.startEndTime
     *
     * @param startendtime the value for calendar.startEndTime
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setStartendtime(String startendtime) {
        this.startendtime = startendtime == null ? null : startendtime.trim();
    }
}