package com.srsoft.model;

public class CalendarType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendarType.id
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendarType.name
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendarType.companyId
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendarType.id
     *
     * @return the value of calendarType.id
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendarType.id
     *
     * @param id the value for calendarType.id
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendarType.name
     *
     * @return the value of calendarType.name
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendarType.name
     *
     * @param name the value for calendarType.name
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendarType.companyId
     *
     * @return the value of calendarType.companyId
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendarType.companyId
     *
     * @param companyid the value for calendarType.companyId
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
}