package com.srsoft.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CalendarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public CalendarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCalendartypeIsNull() {
            addCriterion("calendarType is null");
            return (Criteria) this;
        }

        public Criteria andCalendartypeIsNotNull() {
            addCriterion("calendarType is not null");
            return (Criteria) this;
        }

        public Criteria andCalendartypeEqualTo(Integer value) {
            addCriterion("calendarType =", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeNotEqualTo(Integer value) {
            addCriterion("calendarType <>", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeGreaterThan(Integer value) {
            addCriterion("calendarType >", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("calendarType >=", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeLessThan(Integer value) {
            addCriterion("calendarType <", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeLessThanOrEqualTo(Integer value) {
            addCriterion("calendarType <=", value, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeIn(List<Integer> values) {
            addCriterion("calendarType in", values, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeNotIn(List<Integer> values) {
            addCriterion("calendarType not in", values, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeBetween(Integer value1, Integer value2) {
            addCriterion("calendarType between", value1, value2, "calendartype");
            return (Criteria) this;
        }

        public Criteria andCalendartypeNotBetween(Integer value1, Integer value2) {
            addCriterion("calendarType not between", value1, value2, "calendartype");
            return (Criteria) this;
        }

        public Criteria andEventnameIsNull() {
            addCriterion("eventName is null");
            return (Criteria) this;
        }

        public Criteria andEventnameIsNotNull() {
            addCriterion("eventName is not null");
            return (Criteria) this;
        }

        public Criteria andEventnameEqualTo(String value) {
            addCriterion("eventName =", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotEqualTo(String value) {
            addCriterion("eventName <>", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameGreaterThan(String value) {
            addCriterion("eventName >", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameGreaterThanOrEqualTo(String value) {
            addCriterion("eventName >=", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLessThan(String value) {
            addCriterion("eventName <", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLessThanOrEqualTo(String value) {
            addCriterion("eventName <=", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameLike(String value) {
            addCriterion("eventName like", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotLike(String value) {
            addCriterion("eventName not like", value, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameIn(List<String> values) {
            addCriterion("eventName in", values, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotIn(List<String> values) {
            addCriterion("eventName not in", values, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameBetween(String value1, String value2) {
            addCriterion("eventName between", value1, value2, "eventname");
            return (Criteria) this;
        }

        public Criteria andEventnameNotBetween(String value1, String value2) {
            addCriterion("eventName not between", value1, value2, "eventname");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailIsNull() {
            addCriterion("envetDetail is null");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailIsNotNull() {
            addCriterion("envetDetail is not null");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailEqualTo(String value) {
            addCriterion("envetDetail =", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailNotEqualTo(String value) {
            addCriterion("envetDetail <>", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailGreaterThan(String value) {
            addCriterion("envetDetail >", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailGreaterThanOrEqualTo(String value) {
            addCriterion("envetDetail >=", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailLessThan(String value) {
            addCriterion("envetDetail <", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailLessThanOrEqualTo(String value) {
            addCriterion("envetDetail <=", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailLike(String value) {
            addCriterion("envetDetail like", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailNotLike(String value) {
            addCriterion("envetDetail not like", value, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailIn(List<String> values) {
            addCriterion("envetDetail in", values, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailNotIn(List<String> values) {
            addCriterion("envetDetail not in", values, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailBetween(String value1, String value2) {
            addCriterion("envetDetail between", value1, value2, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andEnvetdetailNotBetween(String value1, String value2) {
            addCriterion("envetDetail not between", value1, value2, "envetdetail");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Integer value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Integer value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Integer value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Integer value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Integer> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Integer> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Integer value1, Integer value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andStartendtimeIsNull() {
            addCriterion("startEndTime is null");
            return (Criteria) this;
        }

        public Criteria andStartendtimeIsNotNull() {
            addCriterion("startEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andStartendtimeEqualTo(String value) {
            addCriterion("startEndTime =", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeNotEqualTo(String value) {
            addCriterion("startEndTime <>", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeGreaterThan(String value) {
            addCriterion("startEndTime >", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeGreaterThanOrEqualTo(String value) {
            addCriterion("startEndTime >=", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeLessThan(String value) {
            addCriterion("startEndTime <", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeLessThanOrEqualTo(String value) {
            addCriterion("startEndTime <=", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeLike(String value) {
            addCriterion("startEndTime like", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeNotLike(String value) {
            addCriterion("startEndTime not like", value, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeIn(List<String> values) {
            addCriterion("startEndTime in", values, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeNotIn(List<String> values) {
            addCriterion("startEndTime not in", values, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeBetween(String value1, String value2) {
            addCriterion("startEndTime between", value1, value2, "startendtime");
            return (Criteria) this;
        }

        public Criteria andStartendtimeNotBetween(String value1, String value2) {
            addCriterion("startEndTime not between", value1, value2, "startendtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 18 05:41:51 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar
     *
     * @mbggenerated Mon Jul 18 05:41:51 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}