package com.srsoft.model;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.companyName
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.ip
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.companyName
     *
     * @return the value of company.companyName
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.companyName
     *
     * @param companyname the value for company.companyName
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.ip
     *
     * @return the value of company.ip
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.ip
     *
     * @param ip the value for company.ip
     *
     * @mbggenerated Tue Jul 19 11:51:40 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}