package com.srsoft.model;

import java.util.Date;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.id
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.catlogId
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Integer catlogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.headerImg
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private String headerimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.title
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.summary
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.url
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.createTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.updateTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.detailGrouping
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Integer detailgrouping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weiz_content.sequence
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.id
     *
     * @return the value of weiz_content.id
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.id
     *
     * @param id the value for weiz_content.id
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.catlogId
     *
     * @return the value of weiz_content.catlogId
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Integer getCatlogid() {
        return catlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.catlogId
     *
     * @param catlogid the value for weiz_content.catlogId
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setCatlogid(Integer catlogid) {
        this.catlogid = catlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.headerImg
     *
     * @return the value of weiz_content.headerImg
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public String getHeaderimg() {
        return headerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.headerImg
     *
     * @param headerimg the value for weiz_content.headerImg
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setHeaderimg(String headerimg) {
        this.headerimg = headerimg == null ? null : headerimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.title
     *
     * @return the value of weiz_content.title
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.title
     *
     * @param title the value for weiz_content.title
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.summary
     *
     * @return the value of weiz_content.summary
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.summary
     *
     * @param summary the value for weiz_content.summary
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.url
     *
     * @return the value of weiz_content.url
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.url
     *
     * @param url the value for weiz_content.url
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.createTime
     *
     * @return the value of weiz_content.createTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.createTime
     *
     * @param createtime the value for weiz_content.createTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.updateTime
     *
     * @return the value of weiz_content.updateTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.updateTime
     *
     * @param updatetime the value for weiz_content.updateTime
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.detailGrouping
     *
     * @return the value of weiz_content.detailGrouping
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Integer getDetailgrouping() {
        return detailgrouping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.detailGrouping
     *
     * @param detailgrouping the value for weiz_content.detailGrouping
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setDetailgrouping(Integer detailgrouping) {
        this.detailgrouping = detailgrouping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weiz_content.sequence
     *
     * @return the value of weiz_content.sequence
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weiz_content.sequence
     *
     * @param sequence the value for weiz_content.sequence
     *
     * @mbggenerated Tue May 10 05:15:18 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}