package com.srsoft.model;

import java.util.Date;

public class Leave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.id
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.userId
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.startTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.endTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.reason
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.createTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.id
     *
     * @return the value of leave.id
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.id
     *
     * @param id the value for leave.id
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.userId
     *
     * @return the value of leave.userId
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.userId
     *
     * @param userid the value for leave.userId
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.startTime
     *
     * @return the value of leave.startTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.startTime
     *
     * @param starttime the value for leave.startTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.endTime
     *
     * @return the value of leave.endTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.endTime
     *
     * @param endtime the value for leave.endTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.reason
     *
     * @return the value of leave.reason
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.reason
     *
     * @param reason the value for leave.reason
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.createTime
     *
     * @return the value of leave.createTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.createTime
     *
     * @param createtime the value for leave.createTime
     *
     * @mbggenerated Wed Jun 29 08:34:15 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}