package com.srsoft.model;

public class Model {
	Integer index;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.id
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.name
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.url
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.id
     *
     * @return the value of model.id
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.id
     *
     * @param id the value for model.id
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.name
     *
     * @return the value of model.name
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.name
     *
     * @param name the value for model.name
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.url
     *
     * @return the value of model.url
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public String getUrl() {
        return url == null ? "" : url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.url
     *
     * @param url the value for model.url
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

	public Integer getIndex() {
		return index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}
    
    
}