package com.srsoft.model;

public class NoticeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticeType.id
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticeType.name
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticeType.id
     *
     * @return the value of noticeType.id
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticeType.id
     *
     * @param id the value for noticeType.id
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticeType.name
     *
     * @return the value of noticeType.name
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticeType.name
     *
     * @param name the value for noticeType.name
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}