package com.srsoft.model;

public class Resources {
	int index;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.id
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.name
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.companyId
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.id
     *
     * @return the value of resources.id
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.id
     *
     * @param id the value for resources.id
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.name
     *
     * @return the value of resources.name
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.name
     *
     * @param name the value for resources.name
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources.companyId
     *
     * @return the value of resources.companyId
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources.companyId
     *
     * @param companyid the value for resources.companyId
     *
     * @mbggenerated Tue Aug 02 16:22:53 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}
    
}