package com.srsoft.model;

public class RolePowerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_power.power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    private Integer power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_power.role
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_power.power
     *
     * @return the value of role_power.power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_power.power
     *
     * @param power the value for role_power.power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_power.role
     *
     * @return the value of role_power.role
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_power.role
     *
     * @param role the value for role_power.role
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}