package com.srsoft.model;

import java.util.Date;

public class Syslog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.id
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.data1
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private String data1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.data2
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private String data2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.data3
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private String data3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.data4
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private String data4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.createTime
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.id
     *
     * @return the value of syslog.id
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.id
     *
     * @param id the value for syslog.id
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.data1
     *
     * @return the value of syslog.data1
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public String getData1() {
        return data1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.data1
     *
     * @param data1 the value for syslog.data1
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setData1(String data1) {
        this.data1 = data1 == null ? null : data1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.data2
     *
     * @return the value of syslog.data2
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public String getData2() {
        return data2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.data2
     *
     * @param data2 the value for syslog.data2
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setData2(String data2) {
        this.data2 = data2 == null ? null : data2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.data3
     *
     * @return the value of syslog.data3
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public String getData3() {
        return data3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.data3
     *
     * @param data3 the value for syslog.data3
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setData3(String data3) {
        this.data3 = data3 == null ? null : data3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.data4
     *
     * @return the value of syslog.data4
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public String getData4() {
        return data4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.data4
     *
     * @param data4 the value for syslog.data4
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setData4(String data4) {
        this.data4 = data4 == null ? null : data4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.createTime
     *
     * @return the value of syslog.createTime
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.createTime
     *
     * @param createtime the value for syslog.createTime
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}