package com.srsoft.model;

public class UserDefinedForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefinedForm.id
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefinedForm.name
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefinedForm.companyId
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefinedForm.attachmentUrl
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    private String attachmenturl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefinedForm.id
     *
     * @return the value of userDefinedForm.id
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefinedForm.id
     *
     * @param id the value for userDefinedForm.id
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefinedForm.name
     *
     * @return the value of userDefinedForm.name
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefinedForm.name
     *
     * @param name the value for userDefinedForm.name
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefinedForm.companyId
     *
     * @return the value of userDefinedForm.companyId
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefinedForm.companyId
     *
     * @param companyid the value for userDefinedForm.companyId
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefinedForm.attachmentUrl
     *
     * @return the value of userDefinedForm.attachmentUrl
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public String getAttachmenturl() {
        return attachmenturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefinedForm.attachmentUrl
     *
     * @param attachmenturl the value for userDefinedForm.attachmentUrl
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    public void setAttachmenturl(String attachmenturl) {
        this.attachmenturl = attachmenturl == null ? null : attachmenturl.trim();
    }
}