package com.srsoft.model;

public class UserDefineFormDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.id
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.udfId
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private Integer udfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.label
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.widgetType
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private Integer widgettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.requireField
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private Integer requirefield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.controlValue
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private String controlvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormDetail.sequence
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.id
     *
     * @return the value of userDefineFormDetail.id
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.id
     *
     * @param id the value for userDefineFormDetail.id
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.udfId
     *
     * @return the value of userDefineFormDetail.udfId
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public Integer getUdfid() {
        return udfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.udfId
     *
     * @param udfid the value for userDefineFormDetail.udfId
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setUdfid(Integer udfid) {
        this.udfid = udfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.label
     *
     * @return the value of userDefineFormDetail.label
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.label
     *
     * @param label the value for userDefineFormDetail.label
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.widgetType
     *
     * @return the value of userDefineFormDetail.widgetType
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public Integer getWidgettype() {
        return widgettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.widgetType
     *
     * @param widgettype the value for userDefineFormDetail.widgetType
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setWidgettype(Integer widgettype) {
        this.widgettype = widgettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.requireField
     *
     * @return the value of userDefineFormDetail.requireField
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public Integer getRequirefield() {
        return requirefield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.requireField
     *
     * @param requirefield the value for userDefineFormDetail.requireField
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setRequirefield(Integer requirefield) {
        this.requirefield = requirefield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.controlValue
     *
     * @return the value of userDefineFormDetail.controlValue
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public String getControlvalue() {
        return controlvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.controlValue
     *
     * @param controlvalue the value for userDefineFormDetail.controlValue
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setControlvalue(String controlvalue) {
        this.controlvalue = controlvalue == null ? null : controlvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormDetail.sequence
     *
     * @return the value of userDefineFormDetail.sequence
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormDetail.sequence
     *
     * @param sequence the value for userDefineFormDetail.sequence
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}