package com.srsoft.model;

public class UserDefineFormInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.id
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.udfId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private Integer udfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg0
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg1
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg2
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg3
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg4
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg5
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg6
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg7
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg8
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.arg9
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private String arg9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userDefineFormInstance.wfiId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    private Integer wfiid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.id
     *
     * @return the value of userDefineFormInstance.id
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.id
     *
     * @param id the value for userDefineFormInstance.id
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.udfId
     *
     * @return the value of userDefineFormInstance.udfId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public Integer getUdfid() {
        return udfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.udfId
     *
     * @param udfid the value for userDefineFormInstance.udfId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setUdfid(Integer udfid) {
        this.udfid = udfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg0
     *
     * @return the value of userDefineFormInstance.arg0
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg0() {
        return arg0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg0
     *
     * @param arg0 the value for userDefineFormInstance.arg0
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg0(String arg0) {
        this.arg0 = arg0 == null ? null : arg0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg1
     *
     * @return the value of userDefineFormInstance.arg1
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg1() {
        return arg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg1
     *
     * @param arg1 the value for userDefineFormInstance.arg1
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg1(String arg1) {
        this.arg1 = arg1 == null ? null : arg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg2
     *
     * @return the value of userDefineFormInstance.arg2
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg2() {
        return arg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg2
     *
     * @param arg2 the value for userDefineFormInstance.arg2
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg2(String arg2) {
        this.arg2 = arg2 == null ? null : arg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg3
     *
     * @return the value of userDefineFormInstance.arg3
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg3() {
        return arg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg3
     *
     * @param arg3 the value for userDefineFormInstance.arg3
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg3(String arg3) {
        this.arg3 = arg3 == null ? null : arg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg4
     *
     * @return the value of userDefineFormInstance.arg4
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg4() {
        return arg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg4
     *
     * @param arg4 the value for userDefineFormInstance.arg4
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg4(String arg4) {
        this.arg4 = arg4 == null ? null : arg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg5
     *
     * @return the value of userDefineFormInstance.arg5
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg5() {
        return arg5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg5
     *
     * @param arg5 the value for userDefineFormInstance.arg5
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg5(String arg5) {
        this.arg5 = arg5 == null ? null : arg5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg6
     *
     * @return the value of userDefineFormInstance.arg6
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg6() {
        return arg6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg6
     *
     * @param arg6 the value for userDefineFormInstance.arg6
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg6(String arg6) {
        this.arg6 = arg6 == null ? null : arg6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg7
     *
     * @return the value of userDefineFormInstance.arg7
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg7() {
        return arg7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg7
     *
     * @param arg7 the value for userDefineFormInstance.arg7
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg7(String arg7) {
        this.arg7 = arg7 == null ? null : arg7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg8
     *
     * @return the value of userDefineFormInstance.arg8
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg8() {
        return arg8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg8
     *
     * @param arg8 the value for userDefineFormInstance.arg8
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg8(String arg8) {
        this.arg8 = arg8 == null ? null : arg8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.arg9
     *
     * @return the value of userDefineFormInstance.arg9
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public String getArg9() {
        return arg9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.arg9
     *
     * @param arg9 the value for userDefineFormInstance.arg9
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setArg9(String arg9) {
        this.arg9 = arg9 == null ? null : arg9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userDefineFormInstance.wfiId
     *
     * @return the value of userDefineFormInstance.wfiId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public Integer getWfiid() {
        return wfiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userDefineFormInstance.wfiId
     *
     * @param wfiid the value for userDefineFormInstance.wfiId
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    public void setWfiid(Integer wfiid) {
        this.wfiid = wfiid;
    }
}