package com.srsoft.model;

public class WorkflowReceiver4cc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowReceiver4cc.id
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowReceiver4cc.workflowId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowReceiver4cc.workflowNodeId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    private Integer workflownodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowReceiver4cc.receiver
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    private Integer receiver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowReceiver4cc.id
     *
     * @return the value of workflowReceiver4cc.id
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowReceiver4cc.id
     *
     * @param id the value for workflowReceiver4cc.id
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowReceiver4cc.workflowId
     *
     * @return the value of workflowReceiver4cc.workflowId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowReceiver4cc.workflowId
     *
     * @param workflowid the value for workflowReceiver4cc.workflowId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowReceiver4cc.workflowNodeId
     *
     * @return the value of workflowReceiver4cc.workflowNodeId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public Integer getWorkflownodeid() {
        return workflownodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowReceiver4cc.workflowNodeId
     *
     * @param workflownodeid the value for workflowReceiver4cc.workflowNodeId
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public void setWorkflownodeid(Integer workflownodeid) {
        this.workflownodeid = workflownodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowReceiver4cc.receiver
     *
     * @return the value of workflowReceiver4cc.receiver
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowReceiver4cc.receiver
     *
     * @param receiver the value for workflowReceiver4cc.receiver
     *
     * @mbggenerated Sat Jul 09 15:07:04 CST 2016
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }
}