package com.srsoft.model;

public class WorkTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.id
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.name
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.startTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.endTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.range
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private String range;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.startDate
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workTime.companyId
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    private Integer companyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.id
     *
     * @return the value of workTime.id
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.id
     *
     * @param id the value for workTime.id
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.name
     *
     * @return the value of workTime.name
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.name
     *
     * @param name the value for workTime.name
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.startTime
     *
     * @return the value of workTime.startTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.startTime
     *
     * @param starttime the value for workTime.startTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.endTime
     *
     * @return the value of workTime.endTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.endTime
     *
     * @param endtime the value for workTime.endTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.range
     *
     * @return the value of workTime.range
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public String getRange() {
        return range;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.range
     *
     * @param range the value for workTime.range
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setRange(String range) {
        this.range = range == null ? null : range.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.startDate
     *
     * @return the value of workTime.startDate
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.startDate
     *
     * @param startdate the value for workTime.startDate
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workTime.companyId
     *
     * @return the value of workTime.companyId
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workTime.companyId
     *
     * @param companyid the value for workTime.companyId
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }
}