package com.srsoft.model;

public class WorkflowNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.id
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.workflowId
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer workflowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.nodeName
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private String nodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.preLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer prelink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.nextLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer nextlink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.displayX
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer displayx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.displayY
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer displayy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.color
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.sequence
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflowNode.receiver
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    private Integer receiver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.id
     *
     * @return the value of workflowNode.id
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.id
     *
     * @param id the value for workflowNode.id
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.workflowId
     *
     * @return the value of workflowNode.workflowId
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getWorkflowid() {
        return workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.workflowId
     *
     * @param workflowid the value for workflowNode.workflowId
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setWorkflowid(Integer workflowid) {
        this.workflowid = workflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.nodeName
     *
     * @return the value of workflowNode.nodeName
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.nodeName
     *
     * @param nodename the value for workflowNode.nodeName
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.preLink
     *
     * @return the value of workflowNode.preLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getPrelink() {
        return prelink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.preLink
     *
     * @param prelink the value for workflowNode.preLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setPrelink(Integer prelink) {
        this.prelink = prelink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.nextLink
     *
     * @return the value of workflowNode.nextLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getNextlink() {
        return nextlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.nextLink
     *
     * @param nextlink the value for workflowNode.nextLink
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setNextlink(Integer nextlink) {
        this.nextlink = nextlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.displayX
     *
     * @return the value of workflowNode.displayX
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getDisplayx() {
        return displayx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.displayX
     *
     * @param displayx the value for workflowNode.displayX
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setDisplayx(Integer displayx) {
        this.displayx = displayx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.displayY
     *
     * @return the value of workflowNode.displayY
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getDisplayy() {
        return displayy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.displayY
     *
     * @param displayy the value for workflowNode.displayY
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setDisplayy(Integer displayy) {
        this.displayy = displayy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.color
     *
     * @return the value of workflowNode.color
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.color
     *
     * @param color the value for workflowNode.color
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.sequence
     *
     * @return the value of workflowNode.sequence
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.sequence
     *
     * @param sequence the value for workflowNode.sequence
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflowNode.receiver
     *
     * @return the value of workflowNode.receiver
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflowNode.receiver
     *
     * @param receiver the value for workflowNode.receiver
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }
}