package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.Attendance;
import com.srsoft.model.AttendanceEx;
import com.srsoft.model.AttendanceExample;
import com.srsoft.model.StatisticsAttendance;

public interface AttendanceMapper {
	List<AttendanceEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer arg2);
	StatisticsAttendance statisticsAttendance4Month(@Param("userId") Integer arg0, @Param("startDate") String arg1, @Param("endDate") String arg2);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int countByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int deleteByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    List<Attendance> selectByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    Attendance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbggenerated Tue Jul 19 11:38:23 CST 2016
     */
    int updateByPrimaryKey(Attendance record);
}