package com.srsoft.dao;

import com.srsoft.model.CalendarType;
import com.srsoft.model.CalendarTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int countByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int deleteByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int insert(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int insertSelective(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    List<CalendarType> selectByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    CalendarType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") CalendarType record, @Param("example") CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int updateByExample(@Param("record") CalendarType record, @Param("example") CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int updateByPrimaryKeySelective(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendarType
     *
     * @mbggenerated Mon Jul 18 05:00:14 CST 2016
     */
    int updateByPrimaryKey(CalendarType record);
}