package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.Model;
import com.srsoft.model.ModelExample;

public interface ModelMapper {
	List<Model> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int countByExample(ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int deleteByExample(ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int insert(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int insertSelective(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    List<Model> selectByExample(ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    Model selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") Model record, @Param("example") ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int updateByExample(@Param("record") Model record, @Param("example") ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int updateByPrimaryKeySelective(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Sun Jun 26 16:46:00 CST 2016
     */
    int updateByPrimaryKey(Model record);
}