package com.srsoft.dao;

import com.srsoft.model.NoticeType;
import com.srsoft.model.NoticeTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int countByExample(NoticeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int deleteByExample(NoticeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int insert(NoticeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int insertSelective(NoticeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    List<NoticeType> selectByExample(NoticeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    NoticeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int updateByExampleSelective(@Param("record") NoticeType record, @Param("example") NoticeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int updateByExample(@Param("record") NoticeType record, @Param("example") NoticeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int updateByPrimaryKeySelective(NoticeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticeType
     *
     * @mbggenerated Sun Jul 17 22:53:45 CST 2016
     */
    int updateByPrimaryKey(NoticeType record);
}