package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.Notice;
import com.srsoft.model.NoticeEx;
import com.srsoft.model.NoticeExample;

public interface NoticeMapper {
	List<NoticeEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId);
	List<NoticeEx> selectAll4employ(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId, @Param("noticeType") Integer noticeType);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbggenerated Sun Jul 17 23:01:36 CST 2016
     */
    int updateByPrimaryKey(Notice record);
}