package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.Power;
import com.srsoft.model.PowerEx;
import com.srsoft.model.PowerExample;

public interface PowerMapper {
	List<PowerEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int countByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int deleteByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    List<Power> selectByExample(PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    Power selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int updateByExample(@Param("record") Power record, @Param("example") PowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Tue Jun 28 03:40:16 CST 2016
     */
    int updateByPrimaryKey(Power record);
}