package com.srsoft.dao;

import com.srsoft.model.RolePowerExample;
import com.srsoft.model.RolePowerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int countByExample(RolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int deleteByExample(RolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int deleteByPrimaryKey(RolePowerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int insert(RolePowerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int insertSelective(RolePowerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    List<RolePowerKey> selectByExample(RolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") RolePowerKey record, @Param("example") RolePowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbggenerated Sat Jun 11 06:42:39 CST 2016
     */
    int updateByExample(@Param("record") RolePowerKey record, @Param("example") RolePowerExample example);
}