package com.srsoft.dao;

import com.srsoft.model.Syslog;
import com.srsoft.model.SyslogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int countByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int deleteByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int insert(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int insertSelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    List<Syslog> selectByExample(SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    Syslog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") Syslog record, @Param("example") SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int updateByExample(@Param("record") Syslog record, @Param("example") SyslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int updateByPrimaryKeySelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Thu Sep 01 16:09:52 CST 2016
     */
    int updateByPrimaryKey(Syslog record);
}