package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.UserDefinedForm;
import com.srsoft.model.UserDefinedFormEx;
import com.srsoft.model.UserDefinedFormExample;

public interface UserDefinedFormMapper {
	List<UserDefinedFormEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int countByExample(UserDefinedFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int deleteByExample(UserDefinedFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int insert(UserDefinedForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int insertSelective(UserDefinedForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    List<UserDefinedForm> selectByExample(UserDefinedFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    UserDefinedForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserDefinedForm record, @Param("example") UserDefinedFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int updateByExample(@Param("record") UserDefinedForm record, @Param("example") UserDefinedFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int updateByPrimaryKeySelective(UserDefinedForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefinedForm
     *
     * @mbggenerated Sat Aug 06 12:08:21 CST 2016
     */
    int updateByPrimaryKey(UserDefinedForm record);
}