package com.srsoft.dao;

import com.srsoft.model.UserDefineFormInstance;
import com.srsoft.model.UserDefineFormInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDefineFormInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int countByExample(UserDefineFormInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int deleteByExample(UserDefineFormInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int insert(UserDefineFormInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int insertSelective(UserDefineFormInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    List<UserDefineFormInstance> selectByExample(UserDefineFormInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    UserDefineFormInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserDefineFormInstance record, @Param("example") UserDefineFormInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int updateByExample(@Param("record") UserDefineFormInstance record, @Param("example") UserDefineFormInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int updateByPrimaryKeySelective(UserDefineFormInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormInstance
     *
     * @mbggenerated Tue Jul 12 17:09:15 CST 2016
     */
    int updateByPrimaryKey(UserDefineFormInstance record);
}