package com.srsoft.dao;

import com.srsoft.model.UserDefineFormDetail;
import com.srsoft.model.UserDefineFormDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDefineFormDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int countByExample(UserDefineFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int deleteByExample(UserDefineFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int insert(UserDefineFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int insertSelective(UserDefineFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    List<UserDefineFormDetail> selectByExample(UserDefineFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    UserDefineFormDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserDefineFormDetail record, @Param("example") UserDefineFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int updateByExample(@Param("record") UserDefineFormDetail record, @Param("example") UserDefineFormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int updateByPrimaryKeySelective(UserDefineFormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userDefineFormDetail
     *
     * @mbggenerated Sat Aug 06 06:53:22 CST 2016
     */
    int updateByPrimaryKey(UserDefineFormDetail record);
}