package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.WorkflowLog;
import com.srsoft.model.WorkflowLogEx;
import com.srsoft.model.WorkflowLogExample;

public interface WorkflowLogMapper {
	List<WorkflowLogEx> selectWorkflowLogByWfi(@Param("start") Integer start, @Param("limit") Integer limit, @Param("wfiId") Integer wfiId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int countByExample(WorkflowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int deleteByExample(WorkflowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int insert(WorkflowLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int insertSelective(WorkflowLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    List<WorkflowLog> selectByExample(WorkflowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    WorkflowLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkflowLog record, @Param("example") WorkflowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int updateByExample(@Param("record") WorkflowLog record, @Param("example") WorkflowLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int updateByPrimaryKeySelective(WorkflowLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowLog
     *
     * @mbggenerated Sun Jul 03 12:46:11 CST 2016
     */
    int updateByPrimaryKey(WorkflowLog record);
}