package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.Workflow;
import com.srsoft.model.WorkflowEx;
import com.srsoft.model.WorkflowExample;

public interface WorkflowMapper {
	List<WorkflowEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int countByExample(WorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int deleteByExample(WorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int insert(Workflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int insertSelective(Workflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    List<Workflow> selectByExample(WorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    Workflow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") Workflow record, @Param("example") WorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int updateByExample(@Param("record") Workflow record, @Param("example") WorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int updateByPrimaryKeySelective(Workflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflow
     *
     * @mbggenerated Sat Jul 09 13:31:32 CST 2016
     */
    int updateByPrimaryKey(Workflow record);
}