package com.srsoft.dao;

import com.srsoft.model.WorkflowNode;
import com.srsoft.model.WorkflowNodeEx;
import com.srsoft.model.WorkflowNodeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WorkflowNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int countByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int deleteByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int insert(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int insertSelective(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    List<WorkflowNode> selectByExample(WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    WorkflowNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkflowNode record, @Param("example") WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int updateByExample(@Param("record") WorkflowNode record, @Param("example") WorkflowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int updateByPrimaryKeySelective(WorkflowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowNode
     *
     * @mbggenerated Sun Jul 03 12:21:14 CST 2016
     */
    int updateByPrimaryKey(WorkflowNode record);

	List<WorkflowNodeEx> queryWorkflowNodeListBywfId(@Param("workflowId") int workflowId);
}