package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.WorkflowInstance;
import com.srsoft.model.WorkflowInstanceEx;
import com.srsoft.model.WorkflowInstanceExample;

public interface WorkflowInstanceMapper {
	List<WorkflowInstanceEx> selectAll4RecycleBin(@Param("start") Integer start, @Param("limit") Integer limit, @Param("userId") Integer userId);
	
	List<WorkflowInstanceEx> selectAll4Archiving(@Param("start") Integer start, @Param("limit") Integer limit, @Param("userId") Integer userId);
	
	WorkflowInstanceEx selectWorkflowInstanceExById(@Param("wfiId") Integer arg0);
	
	List<WorkflowInstanceEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("userId") Integer userId);
	
	List<WorkflowInstanceEx> queryAuditList(@Param("start") Integer start, @Param("limit") Integer limit, @Param("userId") Integer userId);
	
	List<WorkflowInstanceEx> queryCcList(@Param("start") Integer start, @Param("limit") Integer limit, @Param("userId") Integer userId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int countByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int deleteByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int insert(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int insertSelective(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    List<WorkflowInstance> selectByExample(WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    WorkflowInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkflowInstance record, @Param("example") WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int updateByExample(@Param("record") WorkflowInstance record, @Param("example") WorkflowInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int updateByPrimaryKeySelective(WorkflowInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowInstance
     *
     * @mbggenerated Sat Jul 02 15:40:08 CST 2016
     */
    int updateByPrimaryKey(WorkflowInstance record);
}