package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.WorkflowType;
import com.srsoft.model.WorkflowTypeEx;
import com.srsoft.model.WorkflowTypeExample;

public interface WorkflowTypeMapper {
	List<WorkflowTypeEx> queryWorkflowTypeList(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int countByExample(WorkflowTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int deleteByExample(WorkflowTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int insert(WorkflowType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int insertSelective(WorkflowType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    List<WorkflowType> selectByExample(WorkflowTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    WorkflowType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkflowType record, @Param("example") WorkflowTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int updateByExample(@Param("record") WorkflowType record, @Param("example") WorkflowTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int updateByPrimaryKeySelective(WorkflowType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workflowType
     *
     * @mbggenerated Sat Jul 09 08:23:52 CST 2016
     */
    int updateByPrimaryKey(WorkflowType record);
}