package com.srsoft.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srsoft.model.WorkTime;
import com.srsoft.model.WorkTimeEx;
import com.srsoft.model.WorkTimeExample;

public interface WorkTimeMapper {
	WorkTime selectByUserId(int id);
	List<WorkTimeEx> selectAll4Paging(@Param("start") Integer start, @Param("limit") Integer limit, @Param("companyId") Integer companyId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int countByExample(WorkTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int deleteByExample(WorkTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int insert(WorkTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int insertSelective(WorkTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    List<WorkTime> selectByExample(WorkTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    WorkTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkTime record, @Param("example") WorkTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int updateByExample(@Param("record") WorkTime record, @Param("example") WorkTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int updateByPrimaryKeySelective(WorkTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workTime
     *
     * @mbggenerated Sun Jul 17 22:01:58 CST 2016
     */
    int updateByPrimaryKey(WorkTime record);
}